### ISSUE TITLE
Help: How to build/compile Android App from Customized Source?

### ISSUE THREAD

**Issue by trbolexis** [OpenSprinkler/OpenSprinkler-App#100]
As the title suggests:

I've modified the source code in an effort to add more fixed start times to my OpenSprinkler - and now I am wondering how to compile a new app for use on my devices.

I've installed Grunt, and I'm able to build the working directory, but I truly don't know what to do next. I have also read something about "Phone Gap", but I am not at all sure what to do with that.

- Please see my previous post here: https://github.com/OpenSprinkler/OpenSprinkler-Firmware/issues/146

Any help will be appreciated

**Comment by rayshobby** [comment]
You can download the app source, and directly open index.html in a web browser.

**Comment by salbahra** [comment]
Building the app is done using Cordova CLI. For Android, you can run the following commands (this assumes all dependencies are installed including Android Studio):

```sh
npx cordova prepare android
npx cordova run android
```

**Comment by trbolexis** [comment]
Thank you for your response.

I actually built the app successfully a while ago after careful reading and
research. I appreciate your reply, no less!

**Comment by salbahra** [comment]
Ah okay sorry for the delay but glad to hear it worked!
