### ISSUE TITLE
iOS Weather doesnt display correctly

### ISSUE THREAD

**Issue by PipeDeveloper** [OpenSprinkler/OpenSprinkler-App#101]
Hello OpenSprinkler comunity.

The app on iOS doesnt display correctly the weather card. That happened when i upgrade my OpenSprinkler for MQTT feature (im using OpenSprinkler on a raspberry pi 3B).
I got the version: 2.1.8 (4) and i upgrade it to the last one 2.1.9 (4)
![Captura1](https://user-images.githubusercontent.com/35433329/90442773-2a2e6580-e0a9-11ea-9e4f-83b489250dc7.PNG)

On desktop and bigger sceens such iPhone 6+ seems to be showing fine, but on small phones such iphone 5S and SE looks like this:
<img src="https://user-images.githubusercontent.com/35433329/90441567-2a2d6600-e0a7-11ea-9eed-a87b8588d897.png" width="300">

Im not sure about this but on the card, under the weather and temperature, it should be labeled the location. Something like

Sunny 21°C
Your City, Country

But on desktop is something like this:
![Captura](https://user-images.githubusercontent.com/35433329/90442423-9fe60180-e0a8-11ea-9fb0-84c8b96eb308.PNG)

I double check my location configuration and Time zone and its all ok.

**Comment by salbahra** [comment]
Hello! Is this still occuring?

**Comment by PipeDeveloper** [comment]
Yep, I still got it

**Comment by salbahra** [comment]
Thank you, I will try to look into this!

**Comment by lucasec** [comment]
I think this is related to using the "display zoom" function in iOS settings. I have one user who uses that setting in their OS and they report the same.

**Comment by salbahra** [comment]
I believe this issue might be fixed and further more the devices mentioned are likely no longer in use now.

Going to close this ticket but please let us know if this is still occurring.

Thank you!
