### ISSUE TITLE
feature request: turn of for n days

### ISSUE THREAD

**Issue by arnonuem** [OpenSprinkler/OpenSprinkler-App#105]
In the popup of the status page (when selecting the cog) it would be nice to have the option to not just turn off a circuit temporarely but also to turn a circuit off for n days. That would be super helpful.

**Comment by salbahra** [comment]
That seems like a great feature however unfortunately the app repository is not the best place as the feature would depend on the underlying firmware. I would suggest opening the issue there instead.

Thank you!
