### ISSUE TITLE
Add to fdroid

### ISSUE THREAD

**Issue by hockeymikey** [OpenSprinkler/OpenSprinkler-App#107]

**Comment by salbahra** [comment]
No details provided. Closing due to lack of detail.

**Comment by hockeymikey** [comment]
> No details provided. Closing due to lack of detail.

What details are needed? F-droid is an open source repo for Android apps. Opensprinkler is not in the repo, and it should be too. What more is needed? lol. It's self explanatory.

**Comment by kpfleming** [comment]
It was only self-explanatory if the reader knew that 'fdroid' was a reference to F-Droid, which clearly the maintainer did not. Spelling the name properly and providing a link to the site would have been very useful.

**Comment by hockeymikey** [comment]
> It was only self-explanatory if the reader knew that 'fdroid' was a reference to F-Droid, which clearly the maintainer did not. Spelling the name properly and providing a link to the site would have been very useful.

fdroid is the correct spelling. Both are valid. Who hasn't heard of f-droid? And if he didn't one can always search "fdroid" and learn what it is in a few seconds.

**Comment by salbahra** [comment]
I clearly have never heard of it. Now that I have, I don't see it's value and don't plan to proceed.

Next time, please try opening an issue with more detail and explain why I should invest my time in what you think is a worthwhile effort. You did not do this in this PR and have only turned me off from ever supporting F-droid.

Thank you!

**Comment by hockeymikey** [comment]
> I clearly have never heard of it. Now that I have

Which is surprising since this is an opensource app.

> I don't see it's value and don't plan to proceed.

How isn't it valuable to have an open source app on an open source app platform especially since alot of people only use fdroid and not any Gapps or Google play.

> Next time, please try opening an issue with more detail 

Or you can use a search engine. Adding an app to fdroid isn't something magically detailed in it's initial proposal. 

>explain why I should invest my time in what you think is a worthwhile effort. You did not do this in this issue and have only turned me off from ever supporting F-droid.

Well I think it's a pretty obvious decision to make and include into the repo. If you were skeptical I would've anticipated a reply in such fashion and proceed to discuss it's merits or weighing features like a private repo vs using the public one. And why would you be turned off from an open source and privacy respecting app store?
