### ISSUE TITLE
Zoom log timeline

### ISSUE THREAD

**Issue by opensprinklershop** [OpenSprinkler/OpenSprinkler-App#109]
I work with relatively short but more frequent watering cycles. In the logs under Timeline, these times therefore only appear as short dashes. In the web interface on the PC, I can scroll here with the mouse wheel and thus spread the time axis until I have a resolution down to the minute range.

In the Android app and in the web interface on the smartphone, unfortunately, this does not work at first. A horizontal slide gesture is only evaluated as a horizontal shift. A zoom - gesture enlarges the screen as a whole, but does not lead to any spreading of the timeline. This is probably an Android - problem, because no scroll event is triggered by the gesture control (Timeline.jpg - left).
![Timeline](https://user-images.githubusercontent.com/49987292/102219321-9b5b1980-3edf-11eb-9569-6e7ee796d7cb.jpg)

If I now connect a mouse to my smartphone, the spreading of the timeline via scrolling with the mouse wheel works the same way as on the PC (Timeline.jpg - right). In principle, the app can evaluate a scroll event in the same way as the web interface.

In a further development of the app, is there any thought of supporting the spreading of the timeline via a mechanism other than a scroll event so that you don't have to connect a mouse (or does this already exist)?

**Comment by salbahra** [comment]
Unfortunately this is not likely since we use a third party library for this plot. For now, I think the table view is the best option on your android device.

Thank you for your understanding.
