### ISSUE TITLE
Log sorting

### ISSUE THREAD

**Issue by opensprinklershop** [OpenSprinkler/OpenSprinkler-App#110]
In the logs under Table, all events are sorted by the order of their end times. I find this very confusing because I have some switch events that start one after the other and overlap. Is it possible to sort the events also in the order of their start times?

**Comment by salbahra** [comment]
It should be easy enough to make this configurable. Open to PRs if anyone has one otherwise will keep this open and try to address if I have time.

Thank you!

**Comment by salbahra** [comment]
@mellodev has added this in #151
