### ISSUE TITLE
Dependabot alerts for security

### ISSUE THREAD

**Issue by flavio-fernandes** [OpenSprinkler/OpenSprinkler-App#114]
I see a few dependabot alerts for this repo related to package-lock.json
Known security vulnerabilities detected.
Please have these updated asap.

**Comment by salbahra** [comment]
Thank you for the notice. Please keep in mind almost all the warnings are dev dependency issues (such as Grunt dependencies) and don't get incorporated into the app.

With that said, we absolutely want to ensure a safe development environment as well. We will look into what we can upgrade.

Thanks,
Samer
