### ISSUE TITLE
Suggestion: Multiple columns for station list

### ISSUE THREAD

**Issue by rianadon** [OpenSprinkler/OpenSprinkler-App#119]
When testing my fork, @docsparks came up with the great suggestion that it would be helpful for the station list to have multiple columns. That way you need to scroll less, and it's easier to find stations if you know what column they're in.

I hacked together this code snippet:
```css
@media (min-width: 1032px) {
    #os-running-stations, #os-stations-list { columns: 2; }
}
```

which gives this result:

<img width="1130" alt="Screen Shot 2021-05-05 at 3 47 10 PM" src="https://user-images.githubusercontent.com/18223213/117219992-38e5b580-adbb-11eb-8279-cb8777621a2a.png">

The list is lopsided, and while S16 is aligned with the other stations (arguably better than being centered), it doesn't look great either being left-aligned. Also maybe that center divider line should be longer?

Anyways I'm stuck on how this design could be improved,. Or maybe it looks good enough already.

**Comment by salbahra** [comment]
There is a forum post regarding this which I would love to incorporate into a PR if you could help merge the forum user's contribution which I think produces a nice result with yours.

Thank you very much!

**Comment by docsparks** [comment]
::still new here::

**Comment by salbahra** [comment]
Welcome! Apologizes I forgot to link the forum post: https://opensprinkler.com/forums/topic/stations-view-in-two-rows/
