### ISSUE TITLE
iOS App

### ISSUE THREAD

**Issue by hezechiles** [OpenSprinkler/OpenSprinkler-App#121]
Hello together!
Since the last updates of the app on iOS, access to the OSPI no longer works. 
I can no longer access the app locally. However, it works via the Safari browser. 
The app always reports: check the IP and port. I have the settings as follows: "raspi-ip:8080". 
There are no problems with the app on Android. 
Does anyone have an idea? 
Greetings...

**Comment by mkroesen** [comment]
I have the same Problem.

The connection to the internet is realised via OpenVPN and provided by a NGINX proxy. It is secured with HTTP Basic Auth and SSL (Lets Encrypt). If I deactivate Basic Auth, everything works fine.

**Comment by salbahra** [comment]
I had a few customers report this issue to us via support and the solution seemed to be deleting the application off the device and re-installing it again from the App Store. Could you please try this and let us know if it resolves your issues?

Thank you!

**Comment by mkroesen** [comment]
Sorry for the late reply.

Unfortunately, that doesn't seem to work in this case.
I may have found a bug, see the following issue: https://github.com/OpenSprinkler/OpenSprinkler-App/issues/129#issuecomment-1418914038

Thanks!

**Comment by salbahra** [comment]
Since this issue was related to CORS which is well understood at this point I am going to close this issue.

Please let us know if you continue to have issues moving forward.

Thank you!
