### ISSUE TITLE
Adding to F-Droid

### ISSUE THREAD

**Issue by criadoperez** [OpenSprinkler/OpenSprinkler-App#126]
I read the issue about this that was raised a year ago (Issue [#107](https://github.com/OpenSprinkler/OpenSprinkler-App/issues/107))

[F-Droid ](https://f-droid.org) has grown a lot since then, and it's now not only the standard but sometimes the only option to download any apps on the each time more common de-googled phones, like [GrapheneOS](https://grapheneos.org/), [CalyxOS](https://calyxos.org/), etc.

Assuming the team of OpenSprinkler still has no interest in adding the app to F-Droid themselves... I have the following question...

If somebody else, would take the time to build and publish the app on F-Droid following [these](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) steps, would the team of OpenSprinkler be ok with that?

**Comment by salbahra** [comment]
Apologizes but managing yet another App Store listing is not something we can support at this time.

I'm going to close this issue has it did not receive traction over the past few years.

Thank you!

**Comment by IzzySoft** [comment]
Nothing we can do at IzzyOnDroid without the APKs provided by the developers. We always ship those, we don't sign APKs ourselves.
