### ISSUE TITLE
Cannot connect to ospi at FQDN or subdirectory of root

### ISSUE THREAD

**Issue by cbright** [OpenSprinkler/OpenSprinkler-App#13]
I'm trying to connect to my OSPi behind a reverse proxy hosted in a subdirectory. I've tried to enter the following in the IP field:
* FQDN/ospi
* FQDN/ospi/
* FQDN:80/ospi
* FQDN:80/ospi/

All with "use SSL" checked. can the IP field accept FQDNs or subdirectories? If not can support be added?

**Comment by salbahra** [comment]
Hi, Yes it should support subdirectories without the trailing slash (your first and third examples). Which app version are you on and which platform?

**Comment by cbright** [comment]
I was able to get it working by creating a new site. Editing the existing one didn't seem to work.
App Version 1.4.1 Firmware Forked version of 2.2.44-OSPi.

**Comment by salbahra** [comment]
I understand now what might have occurred while upgrading an existing site to use a proxy with SSL. I will try to resolve this issue in the next version.

Thanks!
