### ISSUE TITLE
Interval Days '1' cannot be used with OSPi

### ISSUE THREAD

**Issue by kpfleming** [OpenSprinkler/OpenSprinkler-App#131]
https://github.com/OpenSprinkler/OpenSprinkler-App/blob/b9e6d0a2c6a36e539e2a9c04ea8f762cc39afb17/www/js/main.js#L9136

I've got OSPi installed from the master branch, and this app installed from the master branch, but I can't set 'Interval Days' to 1, only 2 or higher. The code linked above appears to restrict this feature to only OS versions 2.199 or above, but that function always returns false for OSPi, so OSPi users can't get the benefit of this change.

**Comment by rayshobby** [comment]
The checkOSVersion here refers to firmware version. OSPi can run firmware 2.1.9(9) so this should not be a problem for OSPi as long as you update to the latest firmware.
