### ISSUE TITLE
Bottom bar 'last ran station' does not display date/time properly

### ISSUE THREAD

**Issue by kpfleming** [OpenSprinkler/OpenSprinkler-App#132]
App Version: 2.2.5
Firmware: 2.1.9 (3)
Hardware Version: OSPi

I've tested this with both Chromium and Firefox, and also using my local UI server and the public one. In all cases, the bottom bar doesn't display the date/time of the last program run correctly:

![image](https://user-images.githubusercontent.com/305938/166666544-8555ee81-13ed-437f-8a3b-96e09f54111c.png)

When I open the app the date/time displayed are very strange (a 5-digit year), but then a few seconds later the display changes to what is shown above.

**Comment by salbahra** [comment]
Is this still occurring against the latest firmware and app?

If so, please share the /ja reply from the device please.

Thank you!

**Comment by kpfleming** [comment]
Sorry, I can no longer provide assistance on this issue as I stopped using OpenSprinkler some time ago.

**Comment by salbahra** [comment]
Thank you for your update! I can't reproduce this issue and am going to close this then.
