### ISSUE TITLE
Cordova Build Failure - Android - Gradle ?

### ISSUE THREAD

**Issue by trbom5c** [OpenSprinkler/OpenSprinkler-App#138]
I've been trying for a few days to build the UI App, but my "cordova build" keeps failing:
![image](https://github.com/OpenSprinkler/OpenSprinkler-App/assets/140430237/5f8f8181-c597-4e1d-af47-58c8fe581d8d)

I found this in the build.gradle: 
![image](https://github.com/OpenSprinkler/OpenSprinkler-App/assets/140430237/756c09fa-2438-4417-b87b-f5052eb9709b)

... and this in the cdv-gradle-config.json:
![image](https://github.com/OpenSprinkler/OpenSprinkler-App/assets/140430237/9902907f-8b74-40f4-bdec-07723baf0d35)

Does anything appear out of place? 

I did try changing the value in build.gradle to "GRADLE_VERSION" and get a different error when trying to run the build:
![image](https://github.com/OpenSprinkler/OpenSprinkler-App/assets/140430237/137056c3-00cd-4b3a-93de-3e8698e8c1e9)

Does someone have a functional environment config they're wiling to share? 

Thank you for your support with this in advance.

**Comment by salbahra** [comment]
Be sure to clean your Android Studio completely if you have that installed, make sure to have the latest version of the SDK installed and lastly make sure you are using the latest version of Cordova. If you have it installed globally either remove it (I now include it locally) or update it to 12.

Let me know if the issue persists.

**Comment by trbom5c** [comment]
Thank you, @salbahra 

Machine: 

![image](https://github.com/OpenSprinkler/OpenSprinkler-App/assets/140430237/b5e977f7-53be-421b-ac89-9bf96ff0db13)
![image](https://github.com/OpenSprinkler/OpenSprinkler-App/assets/140430237/88374b61-268c-4760-913b-5f542e8dcaa0)

Cordova Version: 12.0.0 (cordova-lib@12.0.1) 

![image](https://github.com/OpenSprinkler/OpenSprinkler-App/assets/140430237/6d92f511-0e97-4fe4-b6d5-0da40c91243b)

Gradle Version: 7.4.2

![image](https://github.com/OpenSprinkler/OpenSprinkler-App/assets/140430237/0dbc904a-e78e-4207-9229-6bc5e848dffc)

I've removed Android Studio from the system entirely; and ensured the most recent Android SDK (cli) has been installed on the system.

`cordova requirements`:
![image](https://github.com/OpenSprinkler/OpenSprinkler-App/assets/140430237/2dd2a6b0-f6d2-4691-a188-ba6a29af88f1)

I am still receiving this error:

![image](https://github.com/OpenSprinkler/OpenSprinkler-App/assets/140430237/4a875d74-7f68-4174-ad9f-fd0912358ab1)

I appreciate your response, and look forward to getting this resolved. Thank you, again!

**Comment by salbahra** [comment]
Please try deleting the `platforms` directory in the cloned repo, removing all old JDK's and gradle versions, updating to the latest Gradle, and then re-adding the Android platform. I would also suggest you just try using Android Studio directly instead of the CLI as I have better luck with that. If you get the issue in Android Studio, try cleaning the project build folder and try again.

**Comment by trbom5c** [comment]
I am still having no luck with this:

![image](https://github.com/OpenSprinkler/OpenSprinkler-App/assets/140430237/b0d7e32b-f196-4efe-aff0-cd0d81fce5c7)

Let me know if there is a way in which I can contract you for individual support and consultation. :)

**Comment by trbom5c** [comment]
.....

I have absolutely no idea why retrying this worked this time ..... 

![image](https://github.com/OpenSprinkler/OpenSprinkler-App/assets/140430237/a0d3b7cd-9dda-4f8c-ab59-9633bf781872)

Thank you very much -- and my proposition for contracted support stands. I have some ideas for firmware and software implementation that I have no idea how to code/build.

**Comment by trbom5c** [comment]
How do I build the front-end app.js?

**Comment by salbahra** [comment]
Glad to hear you were able to get it built and thank you for following up! I have run into this a few times and ultimately a few clean's did the trick. I also have no idea what is going on, to be completely honest.

Regarding contacted support, I apologize but I really don't have the time for that with everything happening on my side. I am happy to support you when I can here for things that everyone could benefit from though.

The public_html files should be populated by `cordova prepare android` step. If you are not seeing them then something is wrong with the prepare step. Is the HTML content completely missing? If so, are you seeing a blank page when loading the Android app?

**Comment by trbom5c** [comment]
Sorry, I meant to ask - Where do I find the built UI files to host on my domain? The built APK appears to be working fine. I currently have no app.js or home.js to put on my server for opening loading my new UI.

https://ui.mydomain.tld/js

Thank you!

**Comment by salbahra** [comment]
To build the UI files, you can simply run `npx grunt makeFW`. This will produce a zip file named `UI.zip` inside of `build/firmware`. This is the file you will need to extract to the destination of your choice.
