### ISSUE TITLE
Repeating program calculation does not correctly handle non-sequential stations

### ISSUE THREAD

**Issue by denisfrench** [OpenSprinkler/OpenSprinkler-App#14]
When I program a mix of sequential and non-sequential stations, the app throws a warning when I try to save and the repeating interval is less than the total back-to-back run time of all the stations, even if some will be on concurrently.

![image](https://cloud.githubusercontent.com/assets/6369250/7445172/af57ba2a-f1e6-11e4-9d21-2c737cfa664a.png)

In the image "Cl" is a non-sequential station, the others are all sequential. There is 0s gap between stations. If the repeat period is 2 hours, the app gives the warning, if I increase it to 2:05 the warning does not appear. I have tried 2:01, 2:02 etc in case there is some unaccounted for delay I am unaware of, but the warning still occurs until the repeat interval equals the total back-to-back run time.

The program preview page handles non-sequential stations correctly, and they switch on and off as intended.

**Comment by salbahra** [comment]
I am unable to replicate this. These are the steps I took:

Reset controller to default settings. This means station delay is 0 and all stations are flagged as sequential. I am using firmware 2.1.4 and app 1.4.2.

1) I unchecked sequential on station 1 and saved.
2) I made a new program using station 1, 2 and 3. 1 is 5 mins, 2 is 5 mins and 3 is 1 hour and 55 mins. I set the repeat time to 2 hours. I set the interval to 5. I got no warning when saving.
3) I made a change to station 3 to 1 hour 56 mins. When I pushed save, the popup appears.
4) I changed it back to 1 hour and 55 mins, no popup.

This is the function that calculates the run time for the program: https://github.com/OpenSprinkler/OpenSprinkler-App/blob/master/www/js/main.js#L4410-4426

**Comment by denisfrench** [comment]
Thanks for trying to replicate this.

I thought I should try and reset everything and try again. I had some trouble actually resetting, with programs and station data persisting despite reset.

In the end I deleted nvm.dat and tried again from scratch, and of course now the problem has gone away.

I have been pulling and recompiling from this repo for a while, so something must have gone awry along the way I guess.

I will make a point of deleting nvm.dat before reporting issues in future, rather than wasting your time again.

Thanks for your help,
Denis.
