### ISSUE TITLE
Missing www/js/app.js file

### ISSUE THREAD

**Issue by yeltnar** [OpenSprinkler/OpenSprinkler-App#142]
www/js/home.js referes to an app.js file. 
https://github.com/OpenSprinkler/OpenSprinkler-App/blob/7cd962c229d06deab9b3e30f8a0a15cde95d14ed/www/js/home.js#L129

However, this file is not present, preventing the UI from loading.

**Comment by rayshobby** [comment]
This file is automatically generated when you build app from the UI. If you run the UI in a browser window it does not require app.js

**Comment by yeltnar** [comment]
When loading https://demo.opensprinkler.com/, app.js is requested from `/js/app.js` shown in the developer tools. I find this to be the same when making the request to the local hardware. 

Could you help me understand where this file comes from? This seems to disagree from your reply regarding the browser.

**Comment by salbahra** [comment]
You are correct and this used to be a part of the build process. We updated it recently to stop doing that (https://github.com/OpenSprinkler/OpenSprinkler-App/commit/5c609164e1e2f5654a858f48d9f148e5f760c4e0) and have not updated demo UI since that update so it's still serving the app.js.

**Comment by salbahra** [comment]
Just wanted to let you know this issue has been closed by updating `home.js` to reference the individual js files correctly now. I have also removed `app.js` from the backend/server.
