### ISSUE TITLE
Cannot remove image

### ISSUE THREAD

**Issue by silverbullettruck2001** [OpenSprinkler/OpenSprinkler-App#144]
I was messing with the ability to add an image to a station.  However, I want to go back to not having any image assigned to a station, but there is no option to remove an image.  I can only change it, but I don't want it set at all anymore.  Can this be done?

**Comment by silverbullettruck2001** [comment]
@jonathan-marsh could you look at this?

**Comment by jonathan-marsh** [comment]
Sorry, I'm not familiar with the mobile app.

**Comment by rayshobby** [comment]
Does this issue have to do with the official OpenSprinkler mobile app, or is this referring to a different app / UI? If you are not sure, could you post a screenshot of what you are referring to?
