### ISSUE TITLE
Debug Developer Assistance

### ISSUE THREAD

**Issue by silverbullettruck2001** [OpenSprinkler/OpenSprinkler-App#145]
I am new to this, but I wanted to try and setup VSCode to run this app locally so I could try making some changes.  Could a basic guide on what is required to do this be added to the `README.md`?  Or at least respond to this issue with the steps/requirements and I could add them as well?

**Comment by rayshobby** [comment]
There is currently no VSCode setup for the UI / app. You can open the code directly in VSCode or any code editor to edit the code.
