### ISSUE TITLE
Add Email Notifications button and Notification Evenets

### ISSUE THREAD

**Issue by starsoccer** [OpenSprinkler/OpenSprinkler-App#147]
Since the new version of open sprinkler on the mobile app Email Notifications is now shown, and notification events seems to still show the old naming for IFTTT Notifications

**Comment by rayshobby** [comment]
Can you be more specific which platform this is referring to? Is it iOS app? Android App? At the moment, all major platforms (including web, iOS, Android) have been updated to UI version 2.4.1, so they should all show email notification button now. Make sure you update to the latest UI version 2.4.1.

**Comment by starsoccer** [comment]
I think this has been resolved now perhaps I wasnt on the newest version.
