### ISSUE TITLE
Porting to other platforms?

### ISSUE THREAD

**Issue by cintema** [OpenSprinkler/OpenSprinkler-App#19]
Hello,

your code looks quite portable.
However, there is no version for my phone yet :(
Porting to Jolla SailfishOS (aka Maemo, Mer, Meego...) could probably be done easily using a qtwebview instance in main and pointing  that to your index.html.
Are you interested in adding Jolla SailfishOS as an additional platform?
Thanks in advance,

 Chris

**Comment by salbahra** [comment]
Hi Chris,

I have to admit I am not familiar with Jolla SailfishOS however according to their website it can run Android applications. If this is the case then support should already be possible. Is this the case? If not, if you can provide some information to support the OS I would be glad to consider it.

Thank you!

**Comment by cintema** [comment]
Hi, thanks for your quick reply!
Yes, it *can* run Android apps - which requires to have the Dalvik-VM running (which of course, since it is a VM, drains the battery). I do my best to keep it switched of most of the time.
Development for SFOS is done in Qt (https://sailfishos.org/develop/) and, of course, free.
As I mentioned in my first posting, simply including your code through a qtwebview instance would probably do the trick. I can try that by myself if you're too busy, but I have to admit that I'm not to familiar with Qt/Qtquick yet and will have to learn it myself :-)
Thanks again!
Chris

**Comment by salbahra** [comment]
Hi Chris,

Ah okay I agree Android binary is not a long term solution as the battery / heat situation would be awful.

I have never worked with Qt either so this seems quite easy but unfortunately seems to carry a steep learning curve for me personally. Time is quite limited for me right now however I would love to help get this working if you are willing to do the research/learning with what is required (developer environment needed, basics of getting a webview up with Qt, how to compile and package for Jolla SailfishOS and also distribution like an app store, is there one?). The app is tailored for Cordova but also works in Google Chrome and Mozilla Firefox apps so it should really support any browser view given (with some relaxed security restrictions).

If you also don't have the time, I might have to let this one sit for a while until some time frees up later.

Thank you!

**Comment by cintema** [comment]
Ok, thanks for your answer! I'm fine with the Android app in the meantime, and now I eventually have a reason to get a closer look into Qt :-)

**Comment by salbahra** [comment]
Okay sounds good, I am going to close this issue for now however once you get started we can reopen this and I can help in adding support.
