### ISSUE TITLE
incorrect translation language

### ISSUE THREAD

**Issue by littleprojects** [OpenSprinkler/OpenSprinkler-App#22]
hi, 

in the menu "edit options" -> "weather control"

the info text for watering % has a incoorect translation in other languages... I have german selectet. but the translation is dutch or so.  :)

**Comment by salbahra** [comment]
Thank you for the report. The language translations are crowd sourced and hosted online, here: https://www.getlocalization.com/OpenSprinkler/

If you are willing, please update the incorrect translation there and I will merge the update into the code before the next release. The specific string you are discussing can be seen here: https://www.getlocalization.com/Sprinklers/editor/22971/#5433017

Thanks!
