### ISSUE TITLE
Manually Control Master Solenoid

### ISSUE THREAD

**Issue by lamiskin** [OpenSprinkler/OpenSprinkler-App#25]
Hello,

I was wondering if it would be possible to manually control the master solenoid. I can't currently see a way to achieve this within the "Manual Control" section.

The reason behind this:
The master valve is between the bore pump and the rest of the watering system. The watering system includes taps and hoses which need to be turned on manually (not via the ospi). Currently to get around this, I need to enable one of the stations, just to use taps around the house.

Any suggestions would be appreciated.

Thanks,
Lachlan

**Comment by rayshobby** [comment]
Hi Lachlan, one way to manually control master valve is to have one station serve as a 'dummy' station that activates the master station. This way, you can open/close that station to activate/deactivate master station.
