### ISSUE TITLE
documentation for interface (REST) with backend

### ISSUE THREAD

**Issue by bedros** [OpenSprinkler/OpenSprinkler-App#31]
where can I find documentation on how this app communicates with ospi firmware

Thanks,

Bedros

**Comment by littleprojects** [comment]
Hi,

The App just load the json Data from the ospi API. You can find the API on the Opensprinkler website under support. 

You can load the JSON object easily via http. 

Did you need more infos? 

Sorry for my bad project doku. 

Bye David

**Comment by bedros** [comment]
your project is awesome, I just searched for opensprinkler  json and found a pdf file at 

https://opensprinkler.freshdesk.com/support/solutions/articles/5000678648-api-document-firmware-2-1-6-current-

I'm looking for a cleaner, python based backend and found https://github.com/Dan-in-CA/SIP but it does not look like it's compatible with ospi http interface, 

my ultimate goal is to have a wireless (wifi) based extension boards based on rpi zero or orange pi lite with wifi which works with base rpi 3, so instead of turning on/off valves using base gpio, send REST api to extension boards over wifi which they turn on/off local valves from local gpio. In my backyard, I only need power wires to each extension board and wifi repeaters.

**Comment by salbahra** [comment]
This repository is for the front-end software and not the backend firmware that runs on the device. Furthermore, an API that's not compatible with our current firmware will not be supported by this UI.

Please use the forums for further feature or hardware suggestions: https://opensprinkler.com/forums.
