### ISSUE TITLE
Feature Request: Keep the last test run time set when starting new test run

### ISSUE THREAD

**Issue by djabi** [OpenSprinkler/OpenSprinkler-App#33]
Currently when a test runs is initiated the test length time is always set to 0. Most of the time the user will try testing different stations for the same period of time. It will be nice if the app remembers the last test run time and start with that instead of 0.

**Comment by salbahra** [comment]
This has been added and will also sync between sites when using the cloud save feature. Will be released in the next update. Thank you!

**Comment by djabi** [comment]
Wow, that was fast. Thank you for making this change.
