### ISSUE TITLE
Feature Request: Test station while holding the test button (instead of entering test time)

### ISSUE THREAD

**Issue by djabi** [OpenSprinkler/OpenSprinkler-App#34]
Currently the only way to test a station is to tap on the test, enter the test time and the start it. Most often the test is done to only check that the stations works well and that requires short time. It might be nice to start the test while the "test" button is pressed (if pressed for more then a tap) and keep the test running until the press is off. This way one can easily control the short test time w/o entering numbers and submitting forms.

**Comment by salbahra** [comment]
I think by adding the feature requested in issue #33 we address the manual runs representing test runs and removed the hassle of defining a time each test now. I believe for now this concern should be addressed. I will keep this in the back of my mind though if I find an easy way to incorporate this without confusion.

Thank you!
