### ISSUE TITLE
Blocks in logs timeline have zero width

### ISSUE THREAD

**Issue by amirv** [OpenSprinkler/OpenSprinkler-App#35]
![screenshot from 2016-06-16 23-09-39](https://cloud.githubusercontent.com/assets/1183024/16131597/a3da4e6e-3417-11e6-989a-f2a88074f32d.png)

Suggested fix in here: https://gist.github.com/amirv/f7a9e17ffcd3fc3f10e22ac82c46fa1d

**Comment by salbahra** [comment]
Incorporated fix in commit 7e85848

Thank you!

**Comment by mikedevita** [comment]
this same issue occurs on the mobile ios app too.

**Comment by salbahra** [comment]
Version 1.6.0? If so, can you provide a screenshot? I ask because I am curious the scale of the graph as the fix for the issue has been applied and present in the current version.

Thank you!

**Comment by mikedevita** [comment]
https://imgur.com/gallery/NFsOa

**Comment by salbahra** [comment]
Can you pinch to zoom? I believe the scale is very small to show you the overall data.

**Comment by mikedevita** [comment]
they do slightly get larger when you zoom in but it's hard to know what program is what on shorter intervals ... suggest maybe have a legend of color to program above or below the table?

**Comment by salbahra** [comment]
Possibly, the view is not ideal hence why the table view exists for mobile.
