### ISSUE TITLE
Adding image resets all other station names

### ISSUE THREAD

**Issue by ntewinkel** [OpenSprinkler/OpenSprinkler-App#36]
Raspberry Pi Software version: SIP 3.1.53 (2016-08-19) (https://github.com/Dan-in-CA/SIP)
Using the Android App: OpenSprinkler 1.6.0

I had all 13 zones set up with custom names, but none had images.
Decided to set an image for zone 13. Took a picture, clicked "submit", and the names for zones 1-12 became the defaults S01, S02, etc. Zone 13, now with image, kept the proper name.

Thanks!

**Comment by salbahra** [comment]
There is no conditional for the station name based on images or not. Please refer to: https://github.com/OpenSprinkler/OpenSprinkler-App/blob/master/www/js/main.js#L4723

Most likely this is an incompatibility with SIP and the mobile app which has limited support for SIP.
