### ISSUE TITLE
timing doesn't match up on the preview program's screen

### ISSUE THREAD

**Issue by mikedevita** [OpenSprinkler/OpenSprinkler-App#37]
I'm mobile when submitting this but the timeline "graph" on preview program's the time doesn't match to current time of the device or the real current time.

current time should be 8:02pm in the screenshot which should be 20:02 on the timeline. 

I know the rpi time is right because the sprinklers still come on at the right time and interval. see the second screenshot which shows the right time on the home screen.
 
![](https://i.imgur.com/nVBY7aJ.png)
![](https://i.imgur.com/uTjJuID.png)
![](https://i.imgur.com/GYfrHNX.png)

**Comment by salbahra** [comment]
This is the code used to calculate the time:

```
now = new Date( controller.settings.devt * 1000 )
currentTime = new Date( now );
currentTime.setMinutes( currentTime.getMinutes() + currentTime.getTimezoneOffset() );
console.log(currentTime);
```

Assuming you can reproduce the issue on Safari (iOS) then please try the following: Plug your iPhone into a computer, enable developer mode in Safari(https://blog.idrsolutions.com/2015/02/remote-debugging-ios-safari-on-os-x-windows-and-linux/), and debug Safari you should be allowed a console to run code on. If you could run the code above it should match what the app is producing and help us understand the issue.

Thank you!

**Comment by mikedevita** [comment]
thanks I'm unavailable for the next two days but will do some troubleshooting this weekend. do you have slack or anything? id be happy to.rroubleshoot and submit a pr if that helps.

**Comment by salbahra** [comment]
You can just update this issue here, do you have any follow up on this issue?

**Comment by salbahra** [comment]
I still cannot reproduce this issue and have not heard back so I am going to close this however feel free to reopen if the issue exists with some data to at least reproduce it.

Thank you!
