### ISSUE TITLE
Changing the source of "Water level"

### ISSUE THREAD

**Issue by nejkica** [OpenSprinkler/OpenSprinkler-App#38]
Hi, 

almost sure, this is not something to talk about here ... 
Is there a way to access the water level value on the front page of the app/web? 
![image](https://user-images.githubusercontent.com/3638153/26915482-7636dce8-4c26-11e7-9c73-a3a1ccea6052.png)

Why do I ask ... My client has rain water tank in which there is a level sensor. I would like to show that value in place of water level. I have a separate web app myself where those values are stored which looks like this:
![image](https://user-images.githubusercontent.com/3638153/26915459-624503fe-4c26-11e7-9781-78ae51caa16e.png)
or like this
![image](https://user-images.githubusercontent.com/3638153/26915566-e622b4d2-4c26-11e7-9846-292e146170bd.png)

But my client always asks why these two are not identical ... although I have explained several times that one has nothing to do with the other.

Anyway, if there is a way to access this number I would like to set this value to water level in the tank.

Thank you for your answers, best regards, Jernej

**Comment by salbahra** [comment]
The code uses the following function to edit the contents of the "Weather Box" `#weather`:

```function updateWeatherBox() {
    $( "#weather" )
        .html( "<div title='" + weather.title + "' class='wicon cond" + weather.code + "'></div>" +
			"<div class='inline tight'>" + weather.temp + "</div><br><div class='inline location tight'>" + weather.location + "</div>" +
			( typeof weather.alert === "object" ? "<div><button class='tight help-icon btn-no-border ui-btn ui-icon-alert ui-btn-icon-notext ui-corner-all'></button>" + weather.alert.type + "</div>" : "" ) )
        .off( "click" ).on( "click", function() {
            changePage( "#forecast" );
            return false;
        } )
        .parents( ".info-card" ).removeClass( "noweather" );
}```

As you can see its source is the `weather` object available globally. If you can modify this variable and call the above function then it should update the values to what you want. However please note if a weather update is triggered (by location change, etc) these values will be overwritten.
