### ISSUE TITLE
On IFTTT integration settings, make the usage a little more intuitive

### ISSUE THREAD

**Issue by andrewshilliday** [OpenSprinkler/OpenSprinkler-App#39]
It took me quite a long time to figure out that the event sent to the Maker Webhook service was "sprinkler".  It would be nice if that was simply stated somewhere in the UI.

Alternatively, it would be convenient to have the trigger name configurable, so that folks with multiple sprinklers can use alternate event trigger names per site.

**Comment by rayshobby** [comment]
The instructions are explained in the OpenSprinkler User Manual:
https://openthings.freshdesk.com/solution/articles/5000716364-user-manuals
page 10 about IFTTT. We can add a link to the user manual.

**Comment by rayshobby** [comment]
In the next version of firmware we will make the IFTTT topic configurable.
