### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by joeinaustin** [OpenSprinkler/OpenSprinkler-App#43]
I believe two files are missing from the cs and js directories.  home.js refers to app.js and app.css.  I do not see those files anywhere.  Am I missing them?

**Comment by salbahra** [comment]
Those are generated by the grunt tasks.

**Comment by joeinaustin** [comment]
Perhaps you can provide more detail for those of us not using Grunt.

**Comment by salbahra** [comment]
To build the app you need Grunt.

**Comment by joeinaustin** [comment]
Perhaps you meant that YOUR process requires Grunt?  I have been working with the Opensprinkler JS code w/o going through the hassle of setting up Grunt but find a few oddities like the one that started this thread.  I think what I hear you saying is that you are unwilling to work w/o, or with those of us w/o Grunt?  That would be unfortunate.  But if correct, perhaps you can go over the complete config/setup of Grunt for this project?  If I am missing something, please elaborate.

**Comment by salbahra** [comment]
I am not sure where the hostility is coming from however Grunt is integral to the packaging process for the application. Not sure why you expect me to give instructions to circumvent the scripts I have written to simplify the packaging. If you want instructions, read the scripts and execute them manually.

Grunt can easily be installed on any platform so it seems like a user choice.

**Comment by joeinaustin** [comment]
Sorry, no hostility intended.  Maybe a little frustration with the one liners.  What I am really looking for are the details to help this project along w/o Grunt.  Definitely a user choice.  It is disappointing to me that it leaves artifacts in the code that further force its use.   I am sure that it seems easy once you have gone through the learning curve of using it.  For me it is a lot of added effort for the simple changes I am trying to test.

**Comment by salbahra** [comment]
I completely understand the frustration. I agree and I would love to ditch
Grunt long term. The good news is we have a developer who is interested in
rewriting the app in a modern framework. I can’t promise any timeline
though. As it stands removing Grunt isn’t something I plan on doing and
supporting building without it isn’t either but if you have a specific
question I can help.

**Comment by joeinaustin** [comment]
I really only have the original question.  W/o setting up Grunt, I don't see those files 2 files.  Perhaps there are more missing that are created by Grunt, but those were the first I ran into.  If I could find a complete set of files created, that would probably allow me to continue work until the rewrite.  I tried pulling them from https://ui.opensprinkler.com/js/ but that was quite messy.   

Any details on the rewrite might also save me some time in the future.

Thank!

**Comment by salbahra** [comment]
If you look at the `Gruntfile.js` you will see `app.js` is a concatenation of `www/js/jquery.js`, `www/js/main.js`, and `www/js/libs.js`. You can concat yourself and uglify it if you want as well. Otherwise, you may reference all three files in that order in the `index.html`.

**Comment by joeinaustin** [comment]
Thank you!
