### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by piousgreek** [OpenSprinkler/OpenSprinkler-App#44]
App displays "network error" shortly after connecting.  I am still able to navigate to logs and other tabs while message is displayed, however I'm unable to issue run once commands, etc.  When i attempt to perform a run once command, it seems like it times out.  I am able to go to the opensprinkler web server using web browser and issue commands from there without any problem.
Raspberry Pi
Linux ospi 4.9.79+ #1086

Note 8
Android version 7.1.1 on Note 8.
Kernel 4.4.21-12461033.

**Comment by salbahra** [comment]
Are you using the SSL option?

**Comment by heegard** [comment]
If you're using SIP, it's probably this issue:
https://github.com/Dan-in-CA/SIP/issues/200
