### ISSUE TITLE
Sprinkler Design Algorithm

### ISSUE THREAD

**Issue by clayellis** [OpenSprinkler/OpenSprinkler-App#47]
Hi 👋 I realize this isn't totally on-topic because it doesn't necessarily have to do with controlling a sprinkler system, more with designing a sprinkler system.

Is anyone aware of an algorithm that can design an optimal sprinkler system (positioning of heads, lines, zoning) given a polygon to fill (representing a yard)?

**Comment by salbahra** [comment]
Going to close this as it likely won't be followed up on here. Please instead post in the forums: https://forums.opensprinkler.com.
