### ISSUE TITLE
Seconds lost in saved program.

### ISSUE THREAD

**Issue by mskressin** [OpenSprinkler/OpenSprinkler-App#51]
I created a program to refill my fountain. When I created the program, I saved the station time as 1 minute and 30 seconds. When I save the program and then re-open the program, the station time is truncated to 1 minute.  I really need to seconds because I need to fine tune the program to deal with evaporation in the fountain.

**Comment by salbahra** [comment]
Which firmware version, app version and hardware are you using?

**Comment by salbahra** [comment]
Can you upgrade your firmware version?

**Comment by mskressin** [comment]
I upgraded to the latest version (2.1.7) and that fixed the problem.
