### ISSUE TITLE
Weather Adjustment Options dialog uses metric units when using Yahoo weather source and US location

### ISSUE THREAD

**Issue by inactivist** [OpenSprinkler/OpenSprinkler-App#53]
Zimmerman Weather Adjustment Method Options dialog shows metric units even though using a US location.  Previously, when using Wunderground.com API key, the settings dialog used English units.

After removing an old Wunderground.com API key, I chose a location (Antioch, Calif. USA) using the in-app map selector.  The weather updates correctly, shows an appropriate weather forecast in main UI.

Later, I opened the Weather Adjustment Options settings.  

![image](https://user-images.githubusercontent.com/1195074/48964226-a4bf6500-ef57-11e8-9f5e-001ed15c3830.png)

https://github.com/OpenSprinkler/OpenSprinkler-App/blob/8cab71818f5fdae4675bf985352a781935b7025f/www/js/main.js#L2323-L2324

Looks like the app now uses Yahoo as weather provider, and `weather.forecast` is truthy (it's an array), but `weather.forecast.region` is undefined, which causes `region` to be `undefined`, and thus `isMetric` to be true.

Here's the current global `weather` object:
```javascript
{
  code: "11"
  forecast: (10) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
  location: "Antioch, CA, US"
  region: "United States"
  source: "yahoo"
  temp: "61&#176;F"
  title: "Showers"
}
```

![image](https://user-images.githubusercontent.com/1195074/48964251-1d262600-ef58-11e8-9f3c-5076b850ff25.png)

App version: 1.8.2
Firmware version: 2.8.1 (1)
![image](https://user-images.githubusercontent.com/1195074/48964185-f74c5180-ef56-11e8-971d-08114d8f17a1.png)

**Comment by PeteBa** [comment]
That's my bad. When I extended the Zimmerman options, I had assumed only wunderground weather service. Looking at the code, I see two things here:
- weather structure is not normalised across providers, i.e. for wunderground, the region is held as ```weather.forecast.region``` whereas for yahoo it is ```weather.region```
- content format is also different as wunderground uses country ISO e.g. "US" whereas yahoo uses country e.g. "United States"

@salbahra , I'll raise a PR for this.

**Comment by inactivist** [comment]
Thanks for the quick response.

Just curious: why try to choose units based on location reported by weather service?  Why not use a user-selectable option instead?   Seems like it'd be lower maintenance.

**Comment by PeteBa** [comment]
That is how it works in a round about way.

The App reads the "loc" field from the OS unit. This can be a text string (e.g. "London, UK"), lat/long or a PWS ID. The App then identifies the corresponding country using either the Yahoo Weather Service or the WUnderground API. The country is then used to select imperial vs metric units.
