### ISSUE TITLE
Removal of WUnderground / Yahoo forecast breaks UI when setup for SSL

### ISSUE THREAD

**Issue by bensweet86** [OpenSprinkler/OpenSprinkler-App#58]
With the change to no longer have forecast data retrieved from WUnderground of Yahoo weather - the web ui no longer works correctly if it has previously been setup for SSL.  Previously WUnderground / Yahoo weather were https endpoints but the opensprinkler endpoint is not.  Error is due to mixed content where the UI (in my example its behind a reverse proxy) has SSL but opensprinkler endpoint (http://weather.opensprinkler.com) does not.
This is also a more painful issue for those self hosting the UI as the firmware and web ui use the same controller.settings.wurl parameter but firmware has no support for https when making weather calls..

**Comment by salbahra** [comment]
I will look into supporting SSL on the Weather Endpoint

**Comment by bensweet86** [comment]
Thanks. I self host the weather script and it works fine as long as the weather endpoint supports http for the firmware calls and https for web ui calls. In my fork there is a slight tweak to the UI so it keeps the same http(s) context

**Comment by salbahra** [comment]
Okay SSL is now turned on for weather.opensprinkler.com: https://weather.opensprinkler.com/

I will update the app and get an update pushed ASAP.

Thanks!
