### ISSUE TITLE
any way to skip the next X hours?

### ISSUE THREAD

**Issue by horacimacias** [OpenSprinkler/OpenSprinkler-App#68]
For example it's raining right now, so I'd like to say "disable for the next 24h" or something along those lines.
Is there any way to do this, besides disabling all programs and remembering to enable them back on 24h later?

**Comment by salbahra** [comment]
You can set the watering level to 0% and change it back when you need. Otherwise no, this would be a firmware request.

**Comment by wepanx** [comment]
@salbahra Isn't this exactly what the "rain delay" functionality does?

**Comment by salbahra** [comment]
Yes you are correct that’s also another option if it’s a known time range.
