### ISSUE TITLE
Translations not applied

### ISSUE THREAD

**Issue by opensprinklershop** [OpenSprinkler/OpenSprinkler-App#81]
1. Some german translation from de.js strings are not used/not working:
- "Water Level" : "% Bewässerung" , but on the screen is for example "Water Level: 111%".
- "Special Station Auto-Refresh": German text exists, but shows english

2. And other strings are not translated:
Location:
"Enter a Location"
"Selected Location"
"Submit"

"Use Metric"

calibration text from "Evapotratranspiration (ET)": "Set the baseline..."
"Baseline ETo"
"Elevation (m)"
"Detetect baseline ETo"

IFTTT:
"Configure Events"

OS 3.0 / App 2.0.3 / Firmware 2.1.8 (6)

**Comment by salbahra** [comment]
Thank you for bringing this to my attention. Although editing current translations is as easy as editing the JSON; generating the new keys is not as easy.

I will add a script to do this in the next update to help get translations going.

**Comment by salbahra** [comment]
We have now moved our translations to Transifex. You can access the strings here: https://www.transifex.com/albahra/opensprinkler/translate/#de/app/289330110?q=text%3Alevel

You might have to register as a translator. If you have any issues doing so please let me know. Once the strings are updated, I will be notified and integrate them with the app.

I am going to close this for now however if you have any issues please re-open.

Thanks!
