### ISSUE TITLE
Adhoc-Program start command sent multiple times in sequence

### ISSUE THREAD

**Issue by Andi-Fwd** [OpenSprinkler/OpenSprinkler-App#82]
First of all thanks a lot for the great OpenSprinkler-App.
I'm using the latest commit 128681b4, build the firmware with grunt makeFW and I'm hosting it on a local webserver on my Raspberry.
I'm running the App from my PC with Firefox (or Chrome does the same) and I configured a normal Program with a few stations assigned.
When I now start this program as an Adhoc-Program the start command is executed multiple times depending on the history of the web page in the browser.
If I reload the App with Ctrl+R, go to the Adhoc-Program and press Save one start command is sent to the OpenSprinkler server. If I start the Adhoc-Program for the 2nd time 2 start commands are sent in sequence to the OpenSprinkler server. If I start the Adhoc-Program for the 3rd time 3 start commands are sent in sequence to the OpenSprinkler server. This scales up until I reload the App again with Ctrl+R.
It seems the OpenSprinkler-App is somehow chaching and then resending all the previous Adhoc-Programs.

Can you reproduce and fix this bug?

**Comment by salbahra** [comment]
Thank you for reporting this! I will take a look at this as soon as I can.

**Comment by salbahra** [comment]
I have tested this recently and cannot reproduce. I have tested on the latest version of Chrome. Could you please try again?
