### ISSUE TITLE
Spanish UI Translate

### ISSUE THREAD

**Issue by PipeDeveloper** [OpenSprinkler/OpenSprinkler-App#83]
Hello!

The web interface and also the App (using from the App store) have a little confusing mistake on the translation English-Spanish.

Mainly on the metric units as time.
Seconds, Minutes, Hours
Segundos, Minutos, Horas
(seg),(min),(h)
respectively

On the image you see a "Run once" set up when i set 20minutes (min) it appears like "20lu"
Seconds appears like "do" but for a better and correct understanding would be "seg"

![Captura](https://user-images.githubusercontent.com/35433329/62244222-fd7bb300-b3ac-11e9-86a9-c48803347f73.PNG)

![Captura1](https://user-images.githubusercontent.com/35433329/62244429-69f6b200-b3ad-11e9-9231-8f5220340195.PNG)

The mobile App appears the same

**Comment by salbahra** [comment]
I transferred this issue to the application where the localization files are. Could you please open a pull request for this change?

Thank you for your contribution!

**Comment by PipeDeveloper** [comment]
Done, Thank you!
-close
