### ISSUE TITLE
Wrong Time Format

### ISSUE THREAD

**Issue by opensprinklershop** [OpenSprinkler/OpenSprinkler-App#93]
The start- and endtime in a opensprinkler program is always US Format, not 24h format
How to reproduce:
- Switch language to german
- Options/Location Select a german city
- System time is showing right, e.G. 01.04.2020 13:21:23
- The go to Options/Programms and select a starttime - time is 12h format!
App Version: 2.1.7
Firmware: 2.1.9 (1)
Hardware Version: OSPI

**Comment by dannybloe** [comment]
Yes indeed. This is very annoying.

**Comment by salbahra** [comment]
This is now fixed and will be deployed soon, thank you!
