### ISSUE TITLE
Baseline ETo not saved

### ISSUE THREAD

**Issue by opensprinklershop** [OpenSprinkler/OpenSprinkler-App#94]
I try to calibrate Wethermethod "Eto", the calibration window has a button "Detect baseline ETo". When I press it, it says "Detected baseline ETo for configured location is 3.05mm/day".
So I press ok - but then BaseLine Eto value returns to 0.
So I try to edit it directory. I enter "3.05" - but then the borders gets red and value is 0.
Same thing with "Elevation" - manuell editing returns to 0.

When I enter baseline=3 and elevation=110 it works. But when I reopen the calibration dialog, value is 0 again.
App Version: 2.1.7
Firmware: 2.1.9 (1)
Hardware Version: OSPI

**Comment by salbahra** [comment]
Thank you for the report! This is now fixed in code and will be deployed ASAP.
